server:
  port: 8080


spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 49.234.192.196:8848

    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service/api/short-link/admin/**
          predicates:
          - Path=/api/short-link/admin/**

        - id: project-service
          uri: lb://project-service/api/short-link/**
          predicates:
          - Path=/api/short-link/**
          
auth:
  excludeUrls:
    - /api/short-link/v1/user/login
    - /api/short-link/v1/user/register
    - /api/short-link/v1/user/check-login
    - /api/short-link/v1/user/has-username

