server:
  port: 8081


spring:
  application:
    name: project-service

  data:
    redis:
      host: 8.153.102.70
      port: 6379
      password: 07030877

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml

  cloud:
    nacos:
      discovery:
        server-addr: 49.234.192.196:8848


  rabbitmq:
    host: 8.153.102.70
    port: 5672
    username: admin
    password: admin

    listener:
      simple:
        retry:
          enabled: true          # 启用重试
          max-attempts: 3        # 最大重试次数
          initial-interval: 1000ms  # 初始重试间隔
          multiplier: 2.0        # 间隔倍数
        acknowledge-mode: manual



mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto