server:
  port: 8081


spring:
  data:
    redis:
      host: 8.153.102.70
      port: 6379
      password: 07030877

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml